services:
  database:
    container_name: database_postgresql
    image: postgres:18.6
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
    env_file:
      - .env


  predictor:
    container_name: predictor_sklearn
    build: ./predictor
    ports:
      - "5000:5000"
    environment:
      API_POST_PREDICT: ${AI_API_POST_PREDICT}
      LOL: "COUCOU!"

  website:
    container_name: website_django
    build: ./website
    ports:
      - "8000:8000"
    depends_on:
      - database
      - predictor
    environment:
      DEBUG: ${DEBUG}

      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      DATABASE_ENGINE: ${DB_ENGINE}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
    env_file:
      - .env
      
volumes:
  postgres_data:
